const QUOTES: { text: string; author: string }[] = [
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "It's not about perfect. It's about effort.", author: "Jillian Michaels" },
  { text: "Small daily improvements over time lead to stunning results.", author: "Robin Sharma" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "A year from now, you'll wish you had started today.", author: "Karen Lamb" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Anonymous" },
  { text: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
  { text: "Your future is created by what you do today, not tomorrow.", author: "Robert Kiyosaki" },
  { text: "Motivation gets you going, but discipline keeps you growing.", author: "John C. Maxwell" },
  { text: "Be stronger than your strongest excuse.", author: "Anonymous" },
  { text: "Progress, not perfection, is what we should be asking of ourselves.", author: "Julia Cameron" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Dream big. Start small. Act now.", author: "Robin Sharma" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "Every accomplishment starts with the decision to try.", author: "John F. Kennedy" },
  { text: "Don't count the days. Make the days count.", author: "Muhammad Ali" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "One task at a time. One day at a time. One step closer.", author: "Anonymous" },
  { text: "Consistency is what transforms average into excellence.", author: "Anonymous" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { text: "It always seems impossible until it is done.", author: "Nelson Mandela" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "We are what we repeatedly do. Excellence is not an act, but a habit.", author: "Aristotle" },
  { text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
  { text: "If you want something you've never had, you must do something you've never done.", author: "Thomas Jefferson" },
  { text: "Your only limit is your mind.", author: "Anonymous" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Anonymous" },
  { text: "Great things never come from comfort zones.", author: "Anonymous" },
  { text: "Set your goals high, and don't stop till you get there.", author: "Bo Jackson" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Anonymous" },
  { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Anonymous" },
  { text: "What seems impossible today will one day become your warm-up.", author: "Anonymous" },
  { text: "Make each day your masterpiece.", author: "John Wooden" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "Success isn't always about greatness. It's about consistency.", author: "Dwayne Johnson" },
  { text: "The only person you are destined to become is the one you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Productivity is never an accident. It is always the result of commitment.", author: "Paul J. Meyer" },
  { text: "Stay focused, go after your dreams and keep moving toward your goals.", author: "LL Cool J" },
  { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { text: "Work hard in silence, let your success be your noise.", author: "Frank Ocean" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "Light tomorrow with today.", author: "Elizabeth Barrett Browning" },
  { text: "Today is a good day to try.", author: "Queer Eye" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Winning isn't everything, but wanting to win is.", author: "Vince Lombardi" },
  { text: "With self-discipline, most anything is possible.", author: "Theodore Roosevelt" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "Go the extra mile. It's never crowded there.", author: "Dr. Wayne D. Dyer" },
  { text: "Hustle beats talent when talent doesn't hustle.", author: "Ross Simmonds" },
  { text: "Keep your face always toward the sunshine and shadows will fall behind you.", author: "Walt Whitman" },
  { text: "You are enough just as you are.", author: "Meghan Markle" },
  { text: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
  { text: "Eat a live frog first thing in the morning and nothing worse will happen to you the rest of the day.", author: "Brian Tracy" },
  { text: "You don't need more time. You need more focus.", author: "Anonymous" },
  { text: "Your habits shape your identity, and your identity shapes your habits.", author: "James Clear" },
  { text: "Every strike brings me closer to the next home run.", author: "Babe Ruth" },
  { text: "Stop being afraid of what could go wrong, and think of what could go right.", author: "Anonymous" },
  { text: "There is no substitute for hard work.", author: "Thomas Edison" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "If you can dream it, you can do it.", author: "Walt Disney" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "The most effective way to do it, is to do it.", author: "Amelia Earhart" },
  { text: "Opportunity is missed by most people because it is dressed in overalls and looks like work.", author: "Thomas Edison" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
];

export function getDailyQuote(date?: Date): { text: string; author: string } {
  const d = date || new Date();
  const dayOfYear = Math.floor(
    (d.getTime() - new Date(d.getFullYear(), 0, 0).getTime()) / (1000 * 60 * 60 * 24)
  );
  return QUOTES[dayOfYear % QUOTES.length];
}
